# Scraping Data

In [1]:
# Library
import yfinance as yf
import pandas as pd

## Gold

In [7]:
# fetch gold price data
df_gold = yf.download(
    "GC=F",
    period="max",
    interval="1d"
)

df_gold.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open Volume
Ticker            GC=F        GC=F        GC=F        GC=F   GC=F
Date
2000-08-30  273.899994  273.899994  273.899994  273.899994      0
2000-08-31  278.299988  278.299988  274.799988  274.799988      0
2000-09-01  277.000000  277.000000  277.000000  277.000000      0
2000-09-05  275.799988  275.799988  275.799988  275.799988      2
2000-09-06  274.200012  274.200012  274.200012  274.200012      0

In [8]:
df_gold.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6446 entries, 2000-08-30 to 2026-05-08
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, GC=F)   6446 non-null   float64
 1   (High, GC=F)    6446 non-null   float64
 2   (Low, GC=F)     6446 non-null   float64
 3   (Open, GC=F)    6446 non-null   float64
 4   (Volume, GC=F)  6446 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 302.2 KB

In [14]:
df_gold.to_csv("data/raw/gold.csv", index=False)

## Currency

In [9]:
df_idr = yf.download(
    "USDIDR=X",
    period="max",
    interval="1d"
)

df_idr.head()

[*********************100%***********************]  1 of 1 completed

Price         Close     High      Low     Open   Volume
Ticker     USDIDR=X USDIDR=X USDIDR=X USDIDR=X USDIDR=X
Date
2001-06-28  11448.0  11565.0  11338.0  11441.0        0
2001-06-29  11390.0  11510.0  11265.0  11370.0        0
2001-07-02  11320.0  11490.0  11215.0  11315.0        0
2001-07-03  11322.0  11455.0  11188.0  11330.0        0
2001-07-04  11365.0  11465.0  11251.0  11355.0        0

In [10]:
df_idr.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6275 entries, 2001-06-28 to 2026-05-08
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Close, USDIDR=X)   6275 non-null   float64
 1   (High, USDIDR=X)    6275 non-null   float64
 2   (Low, USDIDR=X)     6275 non-null   float64
 3   (Open, USDIDR=X)    6275 non-null   float64
 4   (Volume, USDIDR=X)  6275 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 294.1 KB

In [20]:
df_idr.to_csv("data/raw/idr.csv", index=False)

## Oil

In [11]:
df_oil = yf.download(
    "CL=F",
    period="max",
    interval="1d"
)

df_oil.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open Volume
Ticker           CL=F       CL=F       CL=F       CL=F   CL=F
Date
2000-08-23  32.049999  32.799999  31.950001  31.950001  79385
2000-08-24  31.629999  32.240002  31.400000  31.900000  72978
2000-08-25  32.049999  32.099998  31.320000  31.700001  44601
2000-08-28  32.869999  32.919998  31.860001  32.040001  46770
2000-08-29  32.720001  33.029999  32.560001  32.820000  49131

In [12]:
df_oil.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6455 entries, 2000-08-23 to 2026-05-08
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, CL=F)   6455 non-null   float64
 1   (High, CL=F)    6455 non-null   float64
 2   (Low, CL=F)     6455 non-null   float64
 3   (Open, CL=F)    6455 non-null   float64
 4   (Volume, CL=F)  6455 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 302.6 KB

In [24]:
df_oil.to_csv("data/raw/oil.csv", index=False)

## USD Index

In [4]:
df_dxy = yf.download(
    "DX-Y.NYB",
    period="max",
    interval="1d"
)

df_dxy.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume
Ticker        DX-Y.NYB    DX-Y.NYB    DX-Y.NYB    DX-Y.NYB DX-Y.NYB
Date
1971-01-04  120.529999  120.529999  120.529999  120.529999        0
1971-01-05  120.519997  120.519997  120.519997  120.519997        0
1971-01-06  120.489998  120.489998  120.489998  120.489998        0
1971-01-07  120.550003  120.550003  120.550003  120.550003        0
1971-01-08  120.529999  120.529999  120.529999  120.529999        0

In [5]:
df_dxy.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 14055 entries, 1971-01-04 to 2026-05-08
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Close, DX-Y.NYB)   14055 non-null  float64
 1   (High, DX-Y.NYB)    14055 non-null  float64
 2   (Low, DX-Y.NYB)     14055 non-null  float64
 3   (Open, DX-Y.NYB)    14055 non-null  float64
 4   (Volume, DX-Y.NYB)  14055 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 658.8 KB

In [6]:
df_dxy.to_csv("data/raw/dxy.csv", index=False)

# Standarization data

## Rename data

In [13]:
# Gold
df_gold.columns = df_gold.columns.get_level_values(0)

df_gold = df_gold.rename(columns={
    "Close": "gold_close",
    "High": "gold_high",
    "Low": "gold_low",
    "Open": "gold_open",
    "Volume": "gold_volume"
})

# IDR
df_idr.columns = df_idr.columns.get_level_values(0)

df_idr = df_idr.rename(columns={
    "Close": "idr_close",
    "High": "idr_high",
    "Low": "idr_low",
    "Open": "idr_open",
    "Volume": "idr_volume"
})

# Oil
df_oil.columns = df_oil.columns.get_level_values(0)

df_oil = df_oil.rename(columns={
    "Close": "oil_close",
    "High": "oil_high",
    "Low": "oil_low",
    "Open": "oil_open",
    "Volume": "oil_volume"
})

# DXY
df_dxy.columns = df_dxy.columns.get_level_values(0)

df_dxy = df_dxy.rename(columns={
    "Close": "dxy_close",
    "High": "dxy_high",
    "Low": "dxy_low",
    "Open": "dxy_open",
    "Volume": "dxy_volume"
})

In [14]:
# Reset index
df_gold = df_gold.reset_index()
df_idr = df_idr.reset_index()
df_oil = df_oil.reset_index()
df_dxy = df_dxy.reset_index()